# Generated by Django 5.0.6 on 2024-05-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='file_path',
            field=models.CharField(max_length=2048),
        ),
    ]
