# Generated by Django 5.0.6 on 2024-05-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='LearningMaterial',
        ),
    ]
