# Generated by Django 5.0.6 on 2024-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0002_rename_file_learningmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='description',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
