# Generated by Django 5.0.6 on 2024-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0003_alter_learningmaterial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='file_path',
            field=models.CharField(max_length=2048),
        ),
    ]
