# Generated by Django 5.0.6 on 2024-05-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learningmaterial',
            table='learning_material',
        ),
    ]
