# Generated by Django 5.0.6 on 2024-05-17 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_alter_learningmaterial_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='learning_materials',
            field=models.ManyToManyField(to='app.learningmaterial'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
