# Generated by Django 5.0.6 on 2024-05-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='Requested', max_length=20),
        ),
    ]
