# Generated by Django 5.0.6 on 2024-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_canceled_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_email',
            field=models.EmailField(default='88yangkh@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('PAID', 'PAID'), ('CANCELED', 'CANCELED')], default='REQUESTED', max_length=20),
        ),
    ]
