# Generated by Django 5.0.6 on 2024-05-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_to_email_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='to_email',
            new_name='email',
        ),
    ]
