# Generated by Django 5.0.6 on 2024-05-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_learningmaterial_orders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
