# Generated by Django 5.0.6 on 2024-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file_receiving_email',
            field=models.EmailField(default='88yangkh@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
