# Generated by Django 5.0.6 on 2024-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser_avatar_customuser_file_receiving_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='depositor',
            field=models.CharField(default='양경호', max_length=20),
            preserve_default=False,
        ),
    ]
